apiVersion: v1
kind: Service
metadata:
  name: {{env "REPONAME"}}
  namespace: {{env "REPONAME"}}
  labels:
    app: {{env "REPONAME"}}
  annotations:
    # Registers the clusterIP in DNS, so we can reach it by tunnel on its 10./8 address
    external-dns.alpha.kubernetes.io/hostname: {{env "REPONAME"}}.service.{{env "ENV"}}.medialaben.no.
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: {{env "REPONAME"}}
